%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/chayut/Dropbox/2016 Documents/UNSW 4.1/ELEC4120 Thesis/EX3 - NF stat/20160310131409-flowStat.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/10 15:24:18

%% Initialize variables.
filename = './20160310113945-flowStat.csv';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: text (%s)
%   column5: text (%s)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%s%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time = dataArray{:, 1};
cookie = dataArray{:, 2};
VarName3 = dataArray{:, 3};
srcIP = dataArray{:, 4};
dstIP = dataArray{:, 5};
packet_count = dataArray{:, 6};
byte_count = dataArray{:, 7};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;