function [Time,DesIP,DesPort,SrcIP,SrcPort,Len] = mLoadTrace(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,DESIP,DESPORT,SRCIP,SRCPORT,LEN] = IMPORTFILE(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [TIME,DESIP,DESPORT,SRCIP,SRCPORT,LEN] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [Time,DesIP,DesPort,SrcIP,SrcPort,Len] = importfile('Youtube_trace',1, 48070);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/03/04 22:20:39

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end


formatSpec = '%s%s%f%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines',...
    startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec,...
        endRow(block)-startRow(block)+1, 'Delimiter',...
        delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1,...
        'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
Time = dataArray{:, 1};
DesIP = dataArray{:, 2};
DesPort = dataArray{:, 3};
SrcIP = dataArray{:, 4};
SrcPort = dataArray{:, 5};
Len = dataArray{:, 6};


